spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/pmsdb'
    username: 'root'
    password: 'Macac1234!'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: TRACE

security-config:
  jwt-secret: 'secretulMeu'

scraping-config:
  show-browser: true
  browser-args: '--private'

resource-config:
  upload-resource-path: E:\fac\licenta\resources
  profile-image-prefix: \profile
  base-url: http://localhost:8080